apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
  metadata:
    finalizers:
      - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: my-app-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: greeting
          value: Hi! Helm in Argo CD!
    path: my-app
    repoURL: https://github.com/gitops-workshop/helm
    targetRevision: master
  syncPolicy:
    automated: 
      prune: true
