apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: greeting
          value: Hi! Helm in Argo CD!
    path: my-app
    repoURL: https://github.com/gitops-workshop/helm
    targetRevision: v1.0.0
